FROM ubuntu:22.04

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
RUN node -v

RUN npm install && npm run build && npm install -g serve

EXPOSE 5001

CMD ["serve", "-s", "-l", "5001", "build"]